= GitP4Transfer - Git to P4 Migration
Perforce Professional Services <consulting@perforce.com>
:revdate: 2022-02-25
:doctype: book
:icons: font
:toc:
:toclevels: 4
:sectnumlevels: 4
:xrefstyle: full

:sectnums:
== Pre-requisites

* Install recent version of git (2.x)
* Install Python 3.8+ and modules p4python

=== Install Git

* Git
* Git LFS

    sudo yum install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
    sudo yum install git git-lfs
    git --version

=== Clone repo

    cd /hxdepots
    mkdir work
    cd work
    git clone <url>

=== Fetch all LFS objects

. First ensure that git LFS credentials are stored

    git config --global credential.helper store

    $ git branch
    * master

    $ git lfs fetch --all
    fetch: 163739 object(s) found, done.
    fetch: Fetching all references...
    Username for 'https://git.assembla.com': fred.bloggs
    Password for 'https://robert.cowham.p4@git.assembla.com':
    Downloading LFS objects:   4% (6561/163738), 9.1 GB | 100 MB/s

. After the above you can Ctrl+C to abort because credentials should be in place.

    cat ~/.git-credentials

. If you want to check, the re-run the command and you should not be prompted.

    git lfs fetch --all

. Finally you can spawn the fetch which often takes hours:

    nohup git lfs fetch --all > ../fetch.out &


    perforce@ip-10-0-0-151 deadmatter.DeadMatter2021]$ cat ../fetch.out
    fetch: 163739 object(s) found, done.
    fetch: Fetching all references...

. Check for LFS files not found too - all files less than 140 bytes in size:

    find .git/lfs/objects/ -type f -size -140c

=== Install Python3.8

    yum install wget yum-utils make gcc openssl-devel bzip2-devel libffi-devel zlib-devel
    VER="3.8.12"
    wget https://www.python.org/ftp/python/$VER/Python-$VER.tgz 
    tar zxvf Python-$ver.tgz
    cd Python-$ver.tgz
    ./configure
    make install

=== Install GitP4Transfer

. Run the following as `root`:

+
----
cat << EOF > /etc/yum.repos.d/perforce.repo
[Perforce]
name=Perforce
baseurl=http://package.perforce.com/yum/rhel/7/x86_64/
enabled=1
gpgcheck=1
EOF

rpm --import https://package.perforce.com/perforce.pubkey

yum install perforce-p4python3
----

. As normal user `perforce`:

    pip3 install --user requests ruamel.yaml

. Clone the gitp4transfer repo

    git clone https://github.com/perforce/gitp4transfer.git

. Ensure dependencies setup

    cd gitp4transfer
    python3 GitP4Transfer.py -h

. Setup config file

    python3 GitP4Transfer.py --sample-config > transfer_config.yaml

. Do a test of config

    python3 GitP4Transfer.py -c transfer_config.yaml -n

+
Validate log files

. Consider setting up `p4 typemap` as appropriate

. Do a first test of one commit (note this is often quite a big commit!)

    python3 GitP4Transfer.py -c transfer_config.yaml -m1

. Kick off transfer and monitor log/output file

    nohup python3 GitP4Transfer.py -c transfer_config.yaml > out &

=== Perforce structure

. Create appropriate target depot, e.g. `//git_import/repoA/master`

== Things to do

* Adjust unknown_git user
* Date times for changes update
* Interleave in date/time order

== Branch diffs

Generated by:

    git log --first-parent --oneline master > ../b_master.txt

## gitp4transfer - Go program

This uses git's fast-import file format.

Probably won't work for LFS files, although maybe via `git lfs migrate`??

### Todo

* Report on everything
* Write checkpoint (2004.1 format)
  * What will happen with .gz for all files including text? Maybe just use filetypes and fix after upgrades?
* Option to extract all
* Need to rename branches, or remap them
* When extracting file contents, consider multiple refs to same file
** Duplicate - or auto-write branch values?

* Create channels:
** Commits
** Files


Concerns:

* Converts to string - should we leave as bytes?
* Gzip in threads?
* UTF encoding issues?

### Test Scenarios

* Given a root dir, write files
** Make root dir configurable
** For objects, write files as soon as you get a filename? Or at least consider that.
** Gzip or not
** Detect base file formats using magic signatures
** Issue around main/branch files
*** If From: is blank then assume on main/master?
* Specify main/master and follow back commits on that branch

Options:

* Parse files and contents and write out
** Requires changelist numbers - just use Marks from file.
* Option to filter only a subset of files (on any branch)
* Option to filter a single branch
* Mappings - to rename branches